BEGIN;
SET LOCAL search_path = public;

    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      username TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL CHECK(role IN ('ADMIN', 'WAITER')),
      active INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS sessions (
      token_hash TEXT PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at BIGINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS dining_tables (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      number INTEGER NOT NULL UNIQUE CHECK(number > 0),
      current_name TEXT,
      status TEXT NOT NULL DEFAULT 'AVAILABLE' CHECK(status IN ('AVAILABLE', 'OCCUPIED', 'AWAITING_PAYMENT')),
      opened_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      active INTEGER NOT NULL DEFAULT 1
    );
    CREATE TABLE IF NOT EXISTS products (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_id INTEGER NOT NULL REFERENCES categories(id),
      name TEXT NOT NULL,
      price NUMERIC(12,2) NOT NULL CHECK(price >= 0),
      destination TEXT NOT NULL CHECK(destination IN ('KITCHEN', 'BAR')),
      active INTEGER NOT NULL DEFAULT 1
    );
    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      table_id INTEGER NOT NULL REFERENCES dining_tables(id),
      created_by INTEGER NOT NULL REFERENCES users(id),
      status TEXT NOT NULL DEFAULT 'SENT' CHECK(status IN ('SENT', 'CLOSED', 'CANCELLED')),
      sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      closed_at TIMESTAMPTZ,
      table_name TEXT
    );
    CREATE TABLE IF NOT EXISTS order_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id INTEGER REFERENCES products(id),
      name TEXT NOT NULL,
      unit_price NUMERIC(12,2) NOT NULL CHECK(unit_price >= 0),
      quantity INTEGER NOT NULL CHECK(quantity > 0),
      destination TEXT NOT NULL CHECK(destination IN ('KITCHEN', 'BAR')),
      notes TEXT,
      is_custom INTEGER NOT NULL DEFAULT 0
    );
    CREATE INDEX IF NOT EXISTS orders_table_id_idx ON orders(table_id);
    CREATE INDEX IF NOT EXISTS order_items_order_id_idx ON order_items(order_id);
  
CREATE UNIQUE INDEX users_username_lower_idx ON public.users (lower(username));
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.users FROM anon, authenticated;
GRANT ALL ON public.users TO service_role;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.sessions FROM anon, authenticated;
GRANT ALL ON public.sessions TO service_role;
ALTER TABLE public.dining_tables ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dining_tables FROM anon, authenticated;
GRANT ALL ON public.dining_tables TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.categories FROM anon, authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.products FROM anon, authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.orders FROM anon, authenticated;
GRANT ALL ON public.orders TO service_role;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.order_items FROM anon, authenticated;
GRANT ALL ON public.order_items TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE VIEW public.sabom_table_summary WITH (security_invoker = true) AS 
    SELECT t.id, t.number, t.current_name, t.status, t.opened_at,
      COUNT(DISTINCT o.id) AS order_count,
      COALESCE(SUM(oi.unit_price * oi.quantity), 0) AS total
    FROM dining_tables t
    LEFT JOIN orders o ON o.table_id = t.id AND o.status = 'SENT'
    LEFT JOIN order_items oi ON oi.order_id = o.id
    GROUP BY t.id
    ORDER BY t.number
  ;
REVOKE ALL ON public.sabom_table_summary FROM anon, authenticated;
GRANT SELECT ON public.sabom_table_summary TO service_role;

CREATE VIEW public.sabom_active_products WITH (security_invoker = true) AS 
    SELECT p.id, p.name, p.price, p.destination, c.name AS category
    FROM products p
    JOIN categories c ON c.id = p.category_id
    WHERE p.active = 1 AND c.active = 1
    ORDER BY c.id, p.name
  ;
REVOKE ALL ON public.sabom_active_products FROM anon, authenticated;
GRANT SELECT ON public.sabom_active_products TO service_role;

CREATE VIEW public.sabom_sent_orders WITH (security_invoker = true) AS 
    SELECT o.table_id, o.id, o.sent_at, u.name AS created_by,
      COALESCE(SUM(oi.unit_price * oi.quantity), 0) AS total
    FROM orders o
    JOIN users u ON u.id = o.created_by
    LEFT JOIN order_items oi ON oi.order_id = o.id
    WHERE o.status = 'SENT'
    GROUP BY o.id, u.name
    ORDER BY o.id DESC
  ;
REVOKE ALL ON public.sabom_sent_orders FROM anon, authenticated;
GRANT SELECT ON public.sabom_sent_orders TO service_role;

CREATE VIEW public.sabom_night_orders WITH (security_invoker = true) AS 
    SELECT MIN(o.id) AS id, t.number AS table_number,
      COALESCE(o.table_name, 'Mesa ' || t.number) AS table_name,
      o.status AS order_status, t.status AS table_status,
      MIN(o.sent_at) AS first_sent_at, MAX(o.sent_at) AS last_sent_at,
      o.closed_at, string_agg(DISTINCT u.name, ',') AS created_by,
      COUNT(DISTINCT o.id) AS order_count,
      COALESCE(SUM(oi.quantity), 0) AS item_count,
      COALESCE(SUM(oi.unit_price * oi.quantity), 0) AS total
    FROM orders o
    JOIN dining_tables t ON t.id = o.table_id
    JOIN users u ON u.id = o.created_by
    LEFT JOIN order_items oi ON oi.order_id = o.id
    WHERE o.status IN ('SENT', 'CLOSED')
      AND o.sent_at >= ((date_trunc('day', (now() AT TIME ZONE 'America/Sao_Paulo') - interval '6 hours') + interval '6 hours') AT TIME ZONE 'America/Sao_Paulo')
    GROUP BY o.table_id, t.number, t.status, o.status, o.closed_at, o.table_name
    ORDER BY CASE WHEN o.status = 'SENT' THEN 0 ELSE 1 END, MAX(o.sent_at) DESC
  ;
REVOKE ALL ON public.sabom_night_orders FROM anon, authenticated;
GRANT SELECT ON public.sabom_night_orders TO service_role;

CREATE FUNCTION public.sabom_login_user(p_username text) RETURNS jsonb
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT to_jsonb(u) FROM public.users u WHERE lower(username) = lower(p_username) AND active = 1;
$$;

CREATE FUNCTION public.sabom_sent_order_details(p_table_id integer) RETURNS jsonb
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(o) || jsonb_build_object('items',
    (SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY i.id), '[]'::jsonb) FROM public.order_items i WHERE i.order_id = o.id)
  ) ORDER BY o.id DESC), '[]'::jsonb) FROM public.sabom_sent_orders o WHERE o.table_id = p_table_id;
$$;

CREATE FUNCTION public.sabom_night_order_details() RETURNS jsonb
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public AS $$
  SELECT coalesce(jsonb_agg(to_jsonb(o) ORDER BY CASE WHEN o.order_status = 'SENT' THEN 0 ELSE 1 END, o.last_sent_at DESC), '[]'::jsonb)
  FROM public.sabom_night_orders o;
$$;

CREATE FUNCTION public.sabom_send_order(p_table_id integer, p_user_id integer, p_items jsonb) RETURNS integer
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE
  dining public.dining_tables%ROWTYPE;
  product public.products%ROWTYPE;
  item jsonb;
  order_id integer;
  qty numeric;
  price numeric;
  item_name text;
BEGIN
  SELECT * INTO dining FROM public.dining_tables WHERE id = p_table_id FOR UPDATE;
  IF NOT FOUND OR dining.status <> 'OCCUPIED' THEN RAISE EXCEPTION 'A mesa não está aberta para pedidos.'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id = p_user_id AND active = 1) THEN RAISE EXCEPTION 'Usuário inválido.'; END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' THEN RAISE EXCEPTION 'Pedido inválido.'; END IF;
  IF jsonb_array_length(p_items) NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION 'Adicione de 1 a 100 itens.'; END IF;
  INSERT INTO public.orders (table_id, created_by, table_name) VALUES (p_table_id, p_user_id, dining.current_name) RETURNING id INTO order_id;
  FOR item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    qty := (item->>'quantity')::numeric;
    IF qty IS NULL OR qty NOT BETWEEN 1 AND 99 OR trunc(qty) <> qty THEN RAISE EXCEPTION 'Quantidade inválida.'; END IF;
    IF coalesce((item->>'custom')::boolean, false) THEN
      price := (item->>'price')::numeric;
      item_name := btrim(item->>'name');
      IF coalesce(length(item_name), 0) NOT BETWEEN 1 AND 80 OR price IS NULL OR price < 0 OR price > 9999999999.99
        OR coalesce(item->>'destination', '') NOT IN ('KITCHEN', 'BAR') THEN RAISE EXCEPTION 'Item avulso inválido.'; END IF;
      INSERT INTO public.order_items (order_id, name, unit_price, quantity, destination, notes, is_custom)
      VALUES (order_id, item_name, price, qty::integer, item->>'destination', nullif(left(btrim(item->>'notes'), 180), ''), 1);
    ELSE
      SELECT p.* INTO product FROM public.products p JOIN public.categories c ON c.id = p.category_id
      WHERE p.id = (item->>'id')::integer AND p.active = 1 AND c.active = 1;
      IF NOT FOUND THEN RAISE EXCEPTION 'Um dos produtos não está mais disponível.'; END IF;
      INSERT INTO public.order_items (order_id, product_id, name, unit_price, quantity, destination, notes)
      VALUES (order_id, product.id, product.name, product.price, qty::integer, product.destination, nullif(left(btrim(item->>'notes'), 180), ''));
    END IF;
  END LOOP;
  RETURN order_id;
END;
$$;

CREATE FUNCTION public.sabom_checkout(p_table_id integer, p_user_id integer, p_action text) RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public AS $$
DECLARE dining public.dining_tables%ROWTYPE; actor_role text;
BEGIN
  SELECT * INTO dining FROM public.dining_tables WHERE id = p_table_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Mesa não encontrada.'; END IF;
  SELECT role INTO actor_role FROM public.users WHERE id = p_user_id AND active = 1;
  IF actor_role IS NULL THEN RAISE EXCEPTION 'Usuário inválido.'; END IF;
  IF p_action = 'REQUEST' THEN
    IF dining.status <> 'OCCUPIED' THEN RAISE EXCEPTION 'A mesa não está em atendimento.'; END IF;
    UPDATE public.dining_tables SET status = 'AWAITING_PAYMENT' WHERE id = p_table_id;
  ELSIF p_action = 'CONFIRM' THEN
    IF actor_role <> 'ADMIN' THEN RAISE EXCEPTION 'Somente o administrador pode confirmar pagamentos.'; END IF;
    IF dining.status = 'AVAILABLE' THEN RAISE EXCEPTION 'A mesa já está livre.'; END IF;
    UPDATE public.orders SET status = 'CLOSED', closed_at = statement_timestamp() WHERE table_id = p_table_id AND status = 'SENT';
    UPDATE public.dining_tables SET status = 'AVAILABLE', current_name = NULL, opened_at = NULL WHERE id = p_table_id;
  ELSE RAISE EXCEPTION 'Ação inválida.';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.sabom_login_user(text), public.sabom_sent_order_details(integer), public.sabom_night_order_details(), public.sabom_send_order(integer, integer, jsonb), public.sabom_checkout(integer, integer, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sabom_login_user(text), public.sabom_sent_order_details(integer), public.sabom_night_order_details(), public.sabom_send_order(integer, integer, jsonb), public.sabom_checkout(integer, integer, text) TO service_role;
COMMIT;
